---
title: "R Notebook"
output:
  html_document: 
    keep_md: yes
  html_notebook: default
---

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(readxl)
library(ggthemes)
library(magrittr)
```

```{r}
Name<-LETTERS[seq( from = 1, to = 5 )]
GPA <- c(3.5, 2.7, 3.1, 3.2, 2.4)
StudentGPA <- data.frame(Name, GPA)
```


#Question 1
```{r}
#Population of 5, select k=3 - how many combinations?

factorial(5)/(factorial(3)*(factorial(5-3)))



```


#Question 2

```{r fig.width=8.5, fig.height=4}
#Sampling Distribution of Sampling Means
AllSampleSets <- data.frame(t(combn(Name, 3))) %>% mutate(Iteration = row_number())
AllSampleSetsTall<-gather(AllSampleSets, MemberNumber, Name, 1:3)

AllSampleSetsTall <- inner_join(AllSampleSetsTall, StudentGPA, by ="Name")

AllSampleSetsTall %>% group_by(Iteration) %>% summarise(MeanGPA = mean(GPA)) %>% 
  ggplot(aes(x=MeanGPA)) + geom_histogram(bins=4) + theme_light()
```
```{r}
#calculate mean of the sampling distribution
AllSampleSetsTall %>% group_by(Iteration) %>% summarise(MeanGPA = mean(GPA)) %>% group_by() %>% summarise(SampleMean = mean(MeanGPA), SampleSE = sd(MeanGPA)/sqrt(n()))

```

```